export const FormConfig = [
    {
      id: 1,
      type: "input",
      fieldType: "text",
      xs: 12,
      size: "small",
      label: "Username",
      name: "username",
      placeholder: "Enter Username",
      required: true,
    },
    {
      id: 2,
      type: "input",
      fieldType: "text",
      xs: 12,
      size: "small",
      label: "Email Address",
      name: "email",
      placeholder: "Enter your email sadress",
      required: true,
    },
    {
      id: 3,
      type: "input",
      fieldType: "password",
      xs: 12,
      size: "small",
      label: "Password",
      name: "password",
      placeholder: "Enter your password",
      required: true,
    },
  ];
  