export const FORMCONFIG = [
  {
    id: 1,
    type: "input",
    fieldType: "text",
    accessor: "firstname",
    name: "firstname",
    label: "Firstname",
    placeholder: "Enter Firstname",
    required: true,
    size: "small",
    xs: 6,
  },
  {
    id: 2,
    type: "input",
    fieldType: "text",
    accessor: "lastname",
    name: "lastname",
    label: "Lastname",
    placeholder: "Enter Lastname",
    required: true,
    size: "small",
    xs: 6,
  },
  {
    id: 3,
    type: "input",
    fieldType: "email",
    accessor: "email",
    name: "email",
    label: "Email Address",
    placeholder: "Enter Email Address",
    required: true,
    size: "small",
    xs: 6,
    disabled: true,
  },
  {
    id: 4,
    type: "input",
    fieldType: "password",
    accessor: "password",
    name: "password",
    label: "Password",
    placeholder: "Enter Password",
    required: true,
    size: "small",
    xs: 6,
  },
  {
    id: 5,
    type: "input",
    fieldType: "text",
    accessor: "phoneNumber",
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "Enter Phone Number",
    required: false,
    size: "small",
    xs: 6,
  },
];
